### PR TITLE
[JaeRae/AW] handle displaying leaderboard conditionally based on inst…

### PR DESCRIPTION
**Pull request by graearea**
…itutional banner

### CODE REVIEW

**Comment by benjclark** [comment]
Does this mean that, for the ads we do not want to display, we are still sending http requests for the ad and rendering the ad in to the ad slot but we then hide it with css?

**Comment by moddular** [comment]
> Does this mean that, for the ads we do not want to display, we are still sending http requests for the ad and rendering the ad in to the ad slot but we then hide it with css?

It shouldn't do I think, we don't (or shouldn't) trigger loading the ad if it isn't visible. So the idea is the leaderboard is display: none by default - and doesn't load anything. If there is no institutional banner the component will return an element with the u-show-following-ad class - which causes the ad to be displayed and triggers the loading.

**Comment by benjclark** [comment]
> > Does this mean that, for the ads we do not want to display, we are still sending http requests for the ad and rendering the ad in to the ad slot but we then hide it with css?
> 
> It shouldn't do I think, we don't (or shouldn't) trigger loading the ad if it isn't visible. So the idea is the leaderboard is display: none by default - and doesn't load anything. If there is no institutional banner the component will return an element with the u-show-following-ad class - which causes the ad to be displayed and triggers the loading.

Ok great. Yeah, I was wondering if we needed to include some logic in the GPT script in GTM to say don't load this ad slot if classname x exists on the parent element or something like that. But if GPT doesn't load ads if they are display: none by default then all good!

**Review by benjclark — APPROVED** [review]

**Comment by moddular** [comment]
I believe it's true - e.g. I don't think we load anything on mobiles when the ad is hidden. If it's not true, then I'll fix the GPT script :)

**Pull request merged**
