### PR TITLE
Accommodate diff sized logos at breakpoints

### PR DESCRIPTION
**Pull request by jon-stevens**
We try to accommodate different sized logos at different breakpoints. One logo in particular with a lot of whitespace at the end has illustrated a bit of a problem whereby it gets shrunk quite small at smaller breakpoints. 
Below you can see the green-bordered SVG which seems to have been set to have ~40% whitespace?

Screenshot 2021-09-21 at 11 57 51

--->

Screenshot 2021-09-21 at 11 44 32

Screenshot 2021-09-21 at 11 44 19

### CODE REVIEW

**Comment by sturobson** [comment]
Is it possible to improve the source file and remove the whitespace from the SVG?

**Comment by jon-stevens** [comment]
> Is it possible to improve the source file and remove the whitespace from the SVG?

Hey. I would like to! The journal logos come from a branding service. I am not sure where that is actually actually located.
Given the number of journals it is always a possibility that there will be images like this so it's a good idea to try and cater for that. I am going to try and find if I can fix the image file though.

**Comment by ricky-lau** [comment]
I wonder if the logo you have is shared with the one on the journal sites? 
https://www.nature.com/npjmentalhealth/ - this also seems to have the same issue with the extra space.

They get added on pubserv:
https://product-admin.nature.com/admin/products/npjmentalhealth

**Comment by jon-stevens** [comment]
> They get added on pubserv:
> https://product-admin.nature.com/admin/products/npjmentalhealth

Hmm do you know where I could request access?

**Comment by ricky-lau** [comment]
I shall find out! 🔍

**Comment by ricky-lau** [comment]
Turns out I had the power to give access and we looked at editing the logo to remove extra whitespace and made sure it looked ok for the journal site and editorial system.

**Review by ricky-lau — APPROVED** [review]

**Pull request merged**
