### PR TITLE
add colors utility and add keyline to box

### PR DESCRIPTION
**Pull request by ricky-lau**
Added color utility to exposed 'success' green color to fill SVG icon.

Added keyline style for `c-box`.

### CODE REVIEW

**Comment by davidpauljunior** [comment]
I'm a bit confused by this.
'keyline' doesn't align with the 'success' colouring. What's the design of this? I can't picture it.

**Comment by ricky-lau** [comment]
Sorry, I should have made this into two separate PRs. The 'success' and 'keyline' colours are not necessarily linked but are part of the same story.

The mock-up looks like this:

image

**Comment by davidpauljunior** [comment]
Ah I see. Still feels a little confused to me.
E.g. `keyline` modifier in our brand would be the success colour. But my guess is we want this style used in more than this place, e.g. blue one for info box, orange for warning, red for error.

From a design perspective, is this how were handling status messages? 
If so, box--positive (or box--success), box--info, box--warning might handle be better?

**Comment by ricky-lau** [comment]
Renaming `keyline` to align with status messages would be nice. I'll catch up with Rosario and James. There wasn't detail in the ticket about the future uses of this and I picked it up when no one was around... 😢

**Comment by davidpauljunior** [comment]
Cool 👍 👍

**Comment by ricky-lau** [comment]
@davidpauljunior we will be using this for status messages

**Comment by davidpauljunior** [comment]
@ricky-lau Excellent!

**Pull request merged**
